# File .github/workflows/secrets-update.yml
on:
  push:
    branches:
      - loop-action
  workflow_dispatch:

jobs:
  setup:
    if: ${{ startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update secret
        run: | 
          gh variable set TEST_VAR --body "Set from workflow" --repo https://github.com/madbuilds/template-java-library
          gh variable set TEST_VAR --body "Set from workflow" --repo https://github.com/madbuilds/test
          gh variable list
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}