# File .github/workflows/secrets-update.yml
on:
  push:
    branches:
      - loop-action
  workflow_dispatch:

env:
  SOURCE_BRANCH:     master
  SOURCE_REPOSITORY: madbuilds/template-java-library

  PROJECTS: >
    template-java-library

jobs:
  setup:
    if: ${{ startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    steps:
      - name: update secret
        id: secret
        run: |
          gh variable list
          gh variable set TEST_VAR --body "Set from workflow" --org madbuilds --repos ${{ env.PROJECTS }}
          gh variable list
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}