# File .github/workflows/secrets/secrets-update.yml
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

env:
  SOURCE_BRANCH:     master
  SOURCE_REPOSITORY: madbuilds/template-library

  SYNC_APP_ID:        ${{ secrets.MADBUILDS_SYNCAPP_APP_ID }}
  SYNC_CLIENT_ID:     ${{ secrets.MADBUILDS_SYNCAPP_CLIENT_ID }}
  SYNC_CLIENT_SECRET: ${{ secrets.MADBUILDS_SYNCAPP_CLIENT_SECRET }}
  SYNC_PRIVATE_KEY:   ${{ secrets.MADBUILDS_SYNCAPP_PRIVATE_KEY }}
  SYNC_APP_TOKEN:     DUMMY

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Auth # https://github.com/tibdex/github-app-token
        id: auth
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ env.SYNC_APP_ID }}
          private_key: ${{ env.SYNC_PRIVATE_KEY }}
      - name: Setup
        id: matrix
        run: |
          echo "value=[\"a\", \"b\", \"c\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
      - run: |
          echo "SYNC_APP_TOKEN=${{ steps.auth.outputs.token }}" >> $GITHUB_ENV
  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - run: |
          echo "in loop: ${{ matrix.value }}"