# File .github/workflows/secrets-update.yml

# FREE PLAN RESTRICTION: private repos cannot use ORGANIZATION's secrets/vars
# as a workaround, this action synchronize secrets for specific repositories not to do this manually

on:
  workflow_dispatch:

env:
  OWNER_NAME: "madbuilds"
  REPOSITORIES: >
    \"template-java-library\",
    \"test\" \

jobs:
  setup:
    if: ${{ startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.project }}
    steps:
      - name: Setup
        id: matrix
        run: |
          echo "project=[ ${{ env.REPOSITORIES }} ]" >> $GITHUB_OUTPUT
  update:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: update variables
        run: |
          gh repo set-default https://github.com/${{ env.OWNER_NAME }}/${{ matrix.project }}
          
          gh variable set TEST_VAR --body "Set from workflow 5"
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}
      - name: update secrets
        run: | 
          echo <<EOF > PRIVATE_KEY
          ${{ secrets.MADBUILDS_SYNCAPP_PRIVATE_KEY }}
          EOF
          cat PRIVATE_KEY
          echo "file is above:"
          
          gh repo set-default https://github.com/${{ env.OWNER_NAME }}/${{ matrix.project }}
          
          gh secret set MADBUILDS_SYNCAPP_APP_ID        --body ${{ secrets.MADBUILDS_SYNCAPP_APP_ID }}
          gh secret set MADBUILDS_SYNCAPP_CLIENT_ID     --body ${{ secrets.MADBUILDS_SYNCAPP_CLIENT_ID }}
          gh secret set MADBUILDS_SYNCAPP_CLIENT_SECRET --body ${{ secrets.MADBUILDS_SYNCAPP_CLIENT_SECRET }}
          gh secret set MADBUILDS_SYNCAPP_PRIVATE_KEY   < "./PRIVATE_KEY"
          
          rm -f PRIVATE_KEY
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}