# File .github/workflows/secrets-update.yml

# FREE PLAN RESTRICTION: private repos cannot use ORGANIZATION's secrets/vars
# as a workaround, this action synchronize secrets for specific repositories not to do this manually

on:
  push:
    branches:
      - secret-loop
  workflow_dispatch:

env:
  OWNER_NAME: "madbuilds"
  REPOSITORIES: >
    \"template-java-library\",
    \"test\" \

jobs:
  setup:
    if: ${{ startsWith(github.repository, 'madbuilds/template-') }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.project }}
    steps:
      - name: Setup
        id: matrix
        run: |
          echo "project=[             \
              ${{ env.REPOSITORIES }} \
          ]" >> $GITHUB_OUTPUT
  update:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: update secret
        run: | 
          gh variable set TEST_VAR --body "Set from workflow 3" --repo https://github.com/${{ env.OWNER_NAME }}/${{ matrix.project }}
          gh secret   set MYSECRET --body "Set from workflow 3" --repo https://github.com/${{ env.OWNER_NAME }}/${{ matrix.project }}
          gh variable list
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PAT_FULL }}